dist: xenial
services: [docker]
addons:
  apt:
    update: true
    packages:
      - snapd
      - snapcraft
      # - ruby-dev
      # - libffi-dev
      # - make
      # - gcc
      # - g++
      # - git
  snaps:
    - jq
    - yq
    - name: node
      confinement: classic # or devmode
      channel: 10/stable
before_install:
  - openssl aes-256-cbc -K $encrypted_a0f921dc910d_key -iv $encrypted_a0f921dc910d_iv -in snap_token.enc -out snap_token -d
script:
  - docker run -v $(pwd):$(pwd) -w $(pwd) snapcore/snapcraft sh -c "apt update && snapcraft"
  - sudo apt install --yes snapd
  - sudo snap install *.snap --devmode
  - metanorma help
  - for adoc in ./tests/*.adoc; do metanorma compile $adoc; done
deploy:
  skip_cleanup: true
  provider: script
  script:
    - cat snap_token | snapcraft login --with -.
  on:
    branch: master
