dist: xenial
services: [docker]
addons:
  apt:
    update: true
    packages:
      - snapd
      - snapcraft
      # - ruby-dev
      # - libffi-dev
      # - make
      # - gcc
      # - g++
      # - git
  snaps:
    - jq
    - yq
    - name: node
      confinement: classic # or devmode
      channel: 10/stable
before_install:
  - openssl aes-256-cbc -K $encrypted_a0f921dc910d_key -iv $encrypted_a0f921dc910d_iv -in snap_token.enc -out snap_token -d
script:
  # build & install snap
  - docker run -v $(pwd):$(pwd) -w $(pwd) snapcore/snapcraft sh -c "apt update && snapcraft"
  - sudo snap install metanorma_*_amd64.snap --devmode
  - metanorma help
  # install puppeteer
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - curl -L "https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu-install-puppeteer.sh" | sudo bash
  - export NODE_PATH=/usr/lib/node_modules
  # test
  - for adoc in ./tests/*.adoc; do metanorma compile $adoc; done
deploy:
  skip_cleanup: true
  provider: script
  script:
    - cat snap_token | snapcraft login --with -
    - snapcraft push --release=stable metanorma_*_amd64.snap
  on:
    tags: true
    branch: master
