name: metanorma
base: core18
version: '1.1.8'
summary: Metanorma documentation generator
description: |
  Metanorma an open-source framework for writing and publishing standards documents with a focus on semantic authoring and flexible output support. Here’s what you can do with Metanorma: 
  - Build tools for authoring standards and formatting them in accordance with your organization’s practices
  - Use the existing processor ecosystem to create documents compliant to the requirements of ISO, RFC, CalConnect, and others.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  metanorma-cli:
    plugin: gem
    ruby-version: '2.5.5'
    source: https://github.com/metanorma/metanorma-cli.git
    source-tag: v1.1.8
    stage-packages: [git]
  puppeteer:
    plugin: nodejs
    nodejs-version: '11.15.0'
    source: https://github.com/GoogleChrome/puppeteer.git
    source-tag: v1.10.0
    # TODO cut stage-packages below once https://github.com/metanorma/metanorma/pull/70 will be released
    stage-packages: [libx11-6, libx11-xcb1, libxcomposite1, libxcursor1, libxdamage1, libxext6, libxfixes3, libxi6, libxrandr2, libxrender1, libxss1, libxtst6, libnss3, libcups2, libatk1.0-0, libatk-bridge2.0-0, libgdk-pixbuf2.0-0, libglib2.0-0, libgtk-3-0, libasound2]
  plantuml:
    plugin: maven
    maven-version: '3.5.2'
    maven-openjdk-version: '8'
    maven-options: [-DskipTests=true, -Dmaven.javadoc.skip=true]
    source: https://github.com/plantuml/plantuml.git
    source-tag: v1.2019.7
  latexml:
    plugin: cpanm
    cpanm-packages: [LaTeXML@0.8.4]
    stage-packages: [libxml2, libxml2-dev, libxslt1-dev, libicu-dev]
  xml2rfc:
    plugin: python
    python-version: python2
    python-packages: [idnits, xml2rfc]
  idnits:
    plugin: dump
    source: https://tools.ietf.org/tools/idnits/idnits-2.16.02.tgz
apps:
  metanorma:
    environment:
      NODE_PATH: $SNAP/node_modules
      GEM_PATH: $SNAP/lib/ruby/gems/2.5.0
      PATH: $SNAP/idnits:$PATH
    command: ruby $SNAP/bin/metanorma
  plantuml:
    command: java -jar $SNAP/jar/plantuml-1.2019.7-SNAPSHOT.jar