name: main

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:

jobs:
  build:
    name: Build metanorma snap
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft:stable
    steps:
      - uses: actions/checkout@v1
      - name: Snapcraft setup
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools python3 curl
          snapcraft --version
      - name: Build snap
        run: |
          snapcraft snap --debug --output metanorma.snap
      - name: Fix snap
        run: |
          unsquashfs metanorma.snap
          sudo chmod -R g-s ./squashfs-root
          mksquashfs ./squashfs-root ./metanorma_fixed.snap -noappend -comp xz -all-root -no-xattrs -no-fragments
      - uses: actions/upload-artifact@v1
        with:
          name: metanorma-snap
          path: metanorma_fixed.snap

  test:
    name: Test metanorma snap
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Snapcraft setup
        run: |
          sudo apt update
          sudo apt install -y snapd
      - uses: actions/download-artifact@v1
        with:
          name: metanorma-snap
          path: ./snap
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
      - name: Install snap
        run: |
          sudo snap install snap/metanorma_fixed.snap --devmode
      - name: Test snap
        run: |
          for adoc in ./tests/*.adoc; do metanorma compile $adoc; done

  release-edge:
    if: github.ref == 'refs/heads/master'
    name: Release edge snap
    needs: test
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft:stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: metanorma-snap
          path: ./snap
      - name: Push to snapcraft.io
        env:
          SNAPCRAFT_TOKEN: ${{ secrets.snapcraft_token }}
        run: |
          echo "${SNAPCRAFT_TOKEN}" > .snapcraft_token
          snapcraft login --with .snapcraft_token
          snapcraft push --release=edge snap/metanorma_fixed.snap

  release-candidate:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, 'pre')
    name: Release stable snap
    needs: test
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft:stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: metanorma-snap
          path: ./snap
      - name: Push to snapcraft.io
        env:
          SNAPCRAFT_TOKEN: ${{ secrets.snapcraft_token }}
        run: |
          echo "${SNAPCRAFT_TOKEN}" > .snapcraft_token
          snapcraft login --with .snapcraft_token
          snapcraft push --release=candidate snap/metanorma_fixed.snap

  release-stable:
    if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, 'pre')
    name: Release stable snap
    needs: test
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft:stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: metanorma-snap
          path: ./snap
      - name: Push to snapcraft.io
        env:
          SNAPCRAFT_TOKEN: ${{ secrets.snapcraft_token }}
        run: |
          echo "${SNAPCRAFT_TOKEN}" > .snapcraft_token
          snapcraft login --with .snapcraft_token
          snapcraft push --release=stable snap/metanorma_fixed.snap